***On va récupérer les stats des pokés***

In [2]:
#1 on se place 
import os
import ipynbname

chemin_notebook = ipynbname.path()
dossier_notebook = os.path.dirname(chemin_notebook)
os.chdir(dossier_notebook)
os.chdir('../..')
print("Répertoire actuel :", os.getcwd())

Répertoire actuel : /Users/dan2/Desktop/Télécom-master-spé/Projets_perso/Deep/Showdown_AI/my_showdown_ai_git


In [3]:
import json
with open("json/sets.json", "r", encoding="utf-8") as f:
    dict_sets = json.load(f)

296 pokés possibles (omg)

In [4]:
print(dict_sets.keys())

dict_keys(['venusaur', 'charizard', 'blastoise', 'butterfree', 'beedrill', 'pidgeot', 'raticate', 'fearow', 'arbok', 'pikachu', 'raichu', 'sandslash', 'nidoqueen', 'nidoking', 'clefable', 'ninetales', 'wigglytuff', 'vileplume', 'parasect', 'venomoth', 'dugtrio', 'persian', 'golduck', 'primeape', 'arcanine', 'poliwrath', 'alakazam', 'machamp', 'victreebel', 'tentacruel', 'golem', 'rapidash', 'slowbro', 'farfetchd', 'dodrio', 'dewgong', 'muk', 'cloyster', 'gengar', 'hypno', 'kingler', 'electrode', 'exeggutor', 'marowak', 'hitmonlee', 'hitmonchan', 'weezing', 'kangaskhan', 'seaking', 'starmie', 'mrmime', 'scyther', 'jynx', 'pinsir', 'tauros', 'gyarados', 'lapras', 'ditto', 'vaporeon', 'jolteon', 'flareon', 'omastar', 'kabutops', 'aerodactyl', 'snorlax', 'articuno', 'zapdos', 'moltres', 'dragonite', 'mewtwo', 'mew', 'meganium', 'typhlosion', 'feraligatr', 'furret', 'noctowl', 'ledian', 'ariados', 'crobat', 'lanturn', 'xatu', 'ampharos', 'bellossom', 'azumarill', 'sudowoodo', 'politoed', 'j

In [5]:
print(dict_sets["venusaur"])

{'level': 83, 'sets': [{'role': 'Staller', 'movepool': ['leechseed', 'powerwhip', 'sleeppowder', 'sludgebomb', 'substitute'], 'abilities': ['Overgrow']}, {'role': 'Bulky Attacker', 'movepool': ['earthquake', 'leafstorm', 'sleeppowder', 'sludgebomb', 'synthesis'], 'abilities': ['Overgrow']}]}


In [6]:
from poke_env.environment.pokemon import Pokemon


p = Pokemon(gen=4, species="absol")

print(p.type_1.name.lower())

dark


In [7]:
print(type(p.species))

<class 'str'>


In [8]:
print(p.species)

absol


In [9]:
print(p.current_hp)

0


In [10]:
from poke_env.data import GenData
gen_data = GenData.from_gen(4)  # Gen 4
stats = gen_data.pokedex[p.species]["baseStats"]

print(stats)

{'atk': 130, 'def': 60, 'hp': 65, 'spa': 75, 'spd': 60, 'spe': 75}


In [11]:
import numpy as np
hp = stats["hp"]

order = ['atk', 'def', 'spa', 'spd', 'spe']
static_stats = np.array([stats[k] for k in order], dtype=np.float32)

print(static_stats)
print(hp)
print(p.level)

[130.  60.  75.  60.  75.]
65
100


In [12]:
static_stats = np.floor(((2 * static_stats + 31 + (85 // 4)) * p.level) / 100 + 5)

In [13]:
print(static_stats)

[317. 177. 207. 177. 207.]


In [14]:
import math

In [15]:
def get_stats(p) :
    v = np.zeros(6)
    base_stats = gen_data.pokedex[p.species]["baseStats"]

    hp = base_stats["hp"]
    order = ['atk', 'def', 'spa', 'spd', 'spe']
    static_stats = np.array([base_stats[k] for k in order], dtype=np.float32)

    hp = int(math.floor(((2 * hp + 31 + (85 // 4)) * p.level) / 100 + p.level + 10)) #Je fais confiance à p.level, j'espère il va pas me décevoir :O
    static_stats = np.floor(((2 * static_stats + 31 + (85 // 4)) * p.level) / 100 + 5)

    v[0] = hp
    v[-5:] = static_stats

    return v 

In [16]:
print(get_stats(p))

[292. 317. 177. 207. 177. 207.]


***get_stats fonctionnel*** 